[Pkg]
name = "aws_c_io_jll"
uuid = "13c41daa-f319-5298-b5eb-5754e0170d52"
is_jll = true

[Status]
version = "0.26.3+0"

[JLL.products]
library = ["libaws_c_io"]

[[Issues."0.26.3+0"]]
dependent = ["aws_c_http_jll [3254fc65-9028-534d-aa9d-d76d128babc6]"]
dependency = ["aws_c_cal_jll [70f11efc-bab2-57f1-b0f3-22aad4e67c4b]", "aws_c_common_jll [73048d1d-b8c4-5092-a58d-866c5e8d1e50]"]
type = "not_on_latest"
version = "0.26.3+0"
latest = "1.0.0+0"
