
[[Issues."22.1.8+1"]]
dependency = []
dependent = ["OpenCL [08131aa3-fb12-5dee-8b74-c09406e224a2]"]
latest = "23.1.1+0"
type = "not_on_latest"
version = "22.1.8+1"

[[Issues."23.1.1+0"]]
type = "jll_changes"

    [Issues."23.1.1+0".add]
    library = ["libspirv"]

    [Issues."23.1.1+0".remove]
    executable = ["llc"]

[JLL.products]
executable = ["llc"]
[Pkg]
is_jll = true
name = "SPIRV_LLVM_Backend_jll"
uuid = "4376b9bf-cff8-51b6-bb48-39421dff0d0c"

[Status]
version = "22.1.8+1"
