
[[Issues."5.2.3+0"]]
dependency = []
dependent = ["libwebp_jll [c5f90fcd-3b7e-5836-afba-fc50a0988cb2]"]
latest = "6.1.3+0"
type = "not_on_latest"
version = "5.2.3+0"

[JLL.products]
library = ["libgif"]
[Pkg]
is_jll = true
name = "Giflib_jll"
uuid = "59f7168a-df46-5410-90c8-f2779963d0ec"

[Status]
version = "5.2.3+0"
