[Pkg]
name = "Giflib_jll"
uuid = "59f7168a-df46-5410-90c8-f2779963d0ec"
is_jll = true

[Status]
version = "5.2.3+0"

[JLL.products]
library = ["libgif"]

[[Issues."5.2.3+0"]]
dependent = ["libwebp_jll [c5f90fcd-3b7e-5836-afba-fc50a0988cb2]"]
dependency = []
type = "not_on_latest"
version = "5.2.3+0"
latest = "6.1.3+0"
