[Status]
version = "0.10.0"

[[Issues."0.9.5"]]
version = "0.9.5"
type = "not_on_latest"
latest = "0.10.0"
dependent = ["BloqadeSchema [a64e8dd8-bb5a-11ec-104d-290571fc3a8d]"]
dependency = []

[Pkg]
name = "Braket"
uuid = "19504a0f-b47d-4348-9127-acc6cc69ef67"
