[Pkg]
name = "ModelingToolkit"
uuid = "961ee093-0014-501f-94e3-6117800e7a78"

[Status]
version = "11.26.8"

[[Issues."11.35.1"]]
type = "missing_deps"

    [[Issues."11.35.1".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.26.8"]]
type = "missing_deps"

    [[Issues."11.26.8".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"
[[Issues."11.26.8"]]
dependent = []
dependency = ["DiffEqBase [2b5f629d-d688-5b77-993f-72d75c75574e]", "ModelingToolkitBase [7771a370-6774-4173-bd38-47e70ca0b839]", "ModelingToolkitTearing [6bb917b9-1269-42b9-9f7c-b0dca72083ab]", "SciMLBase [0bca4576-84f4-4d90-8ffe-ffa030f20462]"]
type = "not_on_latest"
version = "11.26.8"
latest = "11.39.0"
[[Issues."11.26.8"]]
type = "not_needed"

[[Issues."11.37.1"]]
type = "missing_deps"

    [[Issues."11.37.1".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.39.0"]]
type = "missing_deps"

    [[Issues."11.39.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.28.1"]]
type = "missing_deps"

    [[Issues."11.28.1".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.38.1"]]
type = "missing_deps"

    [[Issues."11.38.1".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.34.1"]]
type = "missing_deps"

    [[Issues."11.34.1".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.38.2"]]
type = "missing_deps"

    [[Issues."11.38.2".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.31.2"]]
type = "missing_deps"

    [[Issues."11.31.2".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.38.0"]]
type = "missing_deps"

    [[Issues."11.38.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.31.0"]]
type = "missing_deps"

    [[Issues."11.31.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.35.0"]]
type = "missing_deps"

    [[Issues."11.35.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.33.0"]]
type = "missing_deps"

    [[Issues."11.33.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.27.0"]]
type = "missing_deps"

    [[Issues."11.27.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.36.0"]]
type = "missing_deps"

    [[Issues."11.36.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.37.0"]]
type = "missing_deps"

    [[Issues."11.37.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.28.2"]]
type = "missing_deps"

    [[Issues."11.28.2".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.31.1"]]
type = "missing_deps"

    [[Issues."11.31.1".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.32.0"]]
type = "missing_deps"

    [[Issues."11.32.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.28.3"]]
type = "missing_deps"

    [[Issues."11.28.3".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.30.1"]]
type = "missing_deps"

    [[Issues."11.30.1".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.29.0"]]
type = "missing_deps"

    [[Issues."11.29.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.28.0"]]
type = "missing_deps"

    [[Issues."11.28.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.34.0"]]
type = "missing_deps"

    [[Issues."11.34.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.35.2"]]
type = "missing_deps"

    [[Issues."11.35.2".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.30.0"]]
type = "missing_deps"

    [[Issues."11.30.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"
