[Status]
version = "2.2.1"

[[Issues."1.5.2"]]
version = "1.5.2"
type = "not_on_latest"
latest = "2.2.1"
dependent = ["HypothesisTests [09f84164-cd44-5f33-b23f-e6b0d136a0d5]"]
dependency = []

[Pkg]
name = "StatsFuns"
uuid = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
