[Pkg]
name = "Roots"
uuid = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[Status]
version = "2.3.0"

[[Issues."2.3.0"]]
type = "missing_deps"

    [[Issues."2.3.0".weak_deps]]
    name = "SymPy"
    uuid = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
[[Issues."2.3.0"]]
dependent = ["BloqadeSchema [a64e8dd8-bb5a-11ec-104d-290571fc3a8d]", "HypothesisTests [09f84164-cd44-5f33-b23f-e6b0d136a0d5]", "PhysicalConstants [5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab]"]
dependency = []
type = "not_on_latest"
version = "2.3.0"
latest = "3.0.0"

[[Issues."3.0.0"]]
type = "missing_deps"

    [[Issues."3.0.0".weak_deps]]
    name = "SymPy"
    uuid = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
