
[[Issues."11.5.16"]]
dependency = []
dependent = ["OpenCL [08131aa3-fb12-5dee-8b74-c09406e224a2]"]
latest = "12.0.2"
type = "not_on_latest"
version = "11.5.16"

[[Issues."12.0.0"]]
type = "missing_deps"

    [[Issues."12.0.0".deps]]
    name = "AcceleratedKernels"
    uuid = "6a4ca0a5-0e36-4168-a932-d9be78d558f1"

[[Issues."12.0.1"]]
type = "missing_deps"

    [[Issues."12.0.1".deps]]
    name = "AcceleratedKernels"
    uuid = "6a4ca0a5-0e36-4168-a932-d9be78d558f1"

[[Issues."12.0.2"]]
type = "missing_deps"

    [[Issues."12.0.2".deps]]
    name = "AcceleratedKernels"
    uuid = "6a4ca0a5-0e36-4168-a932-d9be78d558f1"
[Pkg]
name = "GPUArrays"
uuid = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"

[Status]
version = "11.5.16"
