[Pkg]
name = "SciMLBase"
uuid = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[Status]
version = "2.153.1"

[[Issues."2.154.0"]]
type = "missing_deps"

    [[Issues."2.154.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
    [[Issues."2.154.0".weak_deps]]
    name = "RCall"
    uuid = "6f49c342-dc21-5d91-9882-a32aef131414"

[[Issues."2.153.1"]]
type = "missing_deps"

    [[Issues."2.153.1".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
    [[Issues."2.153.1".weak_deps]]
    name = "RCall"
    uuid = "6f49c342-dc21-5d91-9882-a32aef131414"
[[Issues."2.153.1"]]
dependent = []
dependency = ["FunctionWrappersWrappers [77dc65aa-8811-40c2-897b-53d922fa7daf]"]
type = "not_on_latest"
version = "2.153.1"
latest = "2.154.0"
