[Pkg]
name = "BoundaryValueDiffEqCore"
uuid = "56b672f2-a5fe-4263-ab2d-da677488eb3a"

[Status]
version = "2.1.0"

[[Issues."2.1.0"]]
dependent = []
dependency = ["PreallocationTools [d236fae5-4411-538c-8e31-a6e3d9e00b46]", "SciMLBase [0bca4576-84f4-4d90-8ffe-ffa030f20462]"]
type = "not_on_latest"
version = "2.1.0"
latest = "2.7.4"
