[Pkg]
name = "BoundaryValueDiffEqCore"
uuid = "56b672f2-a5fe-4263-ab2d-da677488eb3a"

[Status]
version = "1.11.1"

[[Issues."2.0.0"]]
type = "missing_deps"

    [[Issues."2.0.0".deps]]
    name = "Integrals"
    uuid = "de52edbc-65ea-441a-8357-d3a637375a31"

[[Issues."1.12.1"]]
type = "missing_deps"

    [[Issues."1.12.1".deps]]
    name = "Integrals"
    uuid = "de52edbc-65ea-441a-8357-d3a637375a31"

[[Issues."1.12.0"]]
type = "missing_deps"

    [[Issues."1.12.0".deps]]
    name = "Integrals"
    uuid = "de52edbc-65ea-441a-8357-d3a637375a31"

[[Issues."2.1.0"]]
type = "missing_deps"

    [[Issues."2.1.0".deps]]
    name = "Integrals"
    uuid = "de52edbc-65ea-441a-8357-d3a637375a31"
