[Pkg]
name = "BoundaryValueDiffEqMIRKN"
uuid = "9255f1d6-53bf-473e-b6bd-23f1ff009da4"

[Status]
version = "1.9.0"

[[Issues."1.9.0"]]
dependent = []
dependency = ["BoundaryValueDiffEqCore [56b672f2-a5fe-4263-ab2d-da677488eb3a]"]
type = "not_on_latest"
version = "1.9.0"
latest = "1.12.0"
