[Pkg]
name = "GettextRuntime_jll"
uuid = "b0724c58-0f36-5564-988d-3bb0596ebc4a"
is_jll = true

[Status]
version = "0.22.4+0"

[JLL.products]
executable = ["envsubst", "gettext", "ngettext"]
library = ["libasprintf", "libintl"]

[[Issues."0.22.4+0"]]
dependent = ["Glib_jll [7746bdde-850d-59dc-9ae8-88ece973131d]"]
dependency = []
type = "not_on_latest"
version = "0.22.4+0"
latest = "1.0.0+0"
