[Pkg]
name = "aws_c_auth_jll"
uuid = "2b3700d1-4306-52e2-a478-c162f0c514be"
is_jll = true

[Status]
version = "0.9.6+0"

[JLL.products]
library = ["libaws_c_auth"]

[[Issues."0.9.6+0"]]
dependent = ["aws_c_s3_jll [bd1f34fb-993f-5903-a121-aaf302eed6d4]"]
dependency = []
type = "not_on_latest"
version = "0.9.6+0"
latest = "0.10.1+0"
