[Pkg]
name = "aws_checksums_jll"
uuid = "b2a88e68-78e7-5e94-8c20-c02986ec140e"
is_jll = true

[Status]
version = "0.2.10+0"

[JLL.products]
library = ["libaws_checksums"]

[[Issues."0.2.10+0"]]
dependent = []
dependency = ["aws_c_common_jll [73048d1d-b8c4-5092-a58d-866c5e8d1e50]"]
type = "not_on_latest"
version = "0.2.10+0"
latest = "0.2.11+0"
