
[[Issues."0.15.1"]]
dependency = ["NLSolversBase [d41bc354-129a-5804-8e4c-c37616107c6c]"]
dependent = []
latest = "0.16.1"
type = "not_on_latest"
version = "0.15.1"
[Pkg]
name = "LsqFit"
required = true
uuid = "2fda8390-95c7-5789-9bda-21331edee243"

[Status]
version = "0.15.1"
