
[JLL.products]
executable = ["bsdcat", "bsdcpio", "bsdtar"]
library = ["libarchive"]
[Pkg]
is_jll = true
name = "LibArchive_jll"
required = true
uuid = "1e303b3e-d4db-56ce-88c4-91e52606a1a8"

[Status]
version = "3.8.9+0"
