[Pkg]
name = "DiffEqBase"
uuid = "2b5f629d-d688-5b77-993f-72d75c75574e"

[Status]
version = "6.213.0"

[[Issues."7.7.0"]]
type = "missing_deps"

    [[Issues."7.7.0".deps]]
    name = "RespecializeParams"
    uuid = "9fe22ead-9e00-4db2-8b46-706a60d40f5e"

    [[Issues."7.7.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.7.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.7.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.7.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.7.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.5.8"]]
type = "missing_deps"

    [[Issues."7.5.8".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.5.8".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.5.8".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.5.8".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.5.8".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."6.214.0"]]
type = "missing_deps"

    [[Issues."6.214.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."6.214.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."6.214.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."6.214.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."6.214.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.5.3"]]
type = "missing_deps"

    [[Issues."7.5.3".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.5.3".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.5.3".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.5.3".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.5.3".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.3.0"]]
type = "missing_deps"

    [[Issues."7.3.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.3.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.3.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.3.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.3.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.10.0"]]
type = "missing_deps"

    [[Issues."7.10.0".deps]]
    name = "RespecializeParams"
    uuid = "9fe22ead-9e00-4db2-8b46-706a60d40f5e"

    [[Issues."7.10.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.10.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.10.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.10.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.10.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.5.5"]]
type = "missing_deps"

    [[Issues."7.5.5".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.5.5".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.5.5".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.5.5".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.5.5".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.2.0"]]
type = "missing_deps"

    [[Issues."7.2.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.2.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.2.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.2.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.2.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."6.213.0"]]
type = "missing_deps"

    [[Issues."6.213.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."6.213.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."6.213.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."6.213.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."6.213.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.8.0"]]
type = "missing_deps"

    [[Issues."7.8.0".deps]]
    name = "RespecializeParams"
    uuid = "9fe22ead-9e00-4db2-8b46-706a60d40f5e"

    [[Issues."7.8.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.8.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.8.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.8.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.8.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."6.218.0"]]
type = "missing_deps"

    [[Issues."6.218.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."6.218.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."6.218.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."6.218.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."6.218.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.4.2"]]
type = "missing_deps"

    [[Issues."7.4.2".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.4.2".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.4.2".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.4.2".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.4.2".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."6.217.0"]]
type = "missing_deps"

    [[Issues."6.217.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."6.217.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."6.217.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."6.217.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."6.217.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.5.4"]]
type = "missing_deps"

    [[Issues."7.5.4".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.5.4".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.5.4".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.5.4".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.5.4".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.5.6"]]
type = "missing_deps"

    [[Issues."7.5.6".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.5.6".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.5.6".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.5.6".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.5.6".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.6.2"]]
type = "missing_deps"

    [[Issues."7.6.2".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.6.2".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.6.2".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.6.2".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.6.2".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.4.1"]]
type = "missing_deps"

    [[Issues."7.4.1".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.4.1".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.4.1".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.4.1".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.4.1".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.2.1"]]
type = "missing_deps"

    [[Issues."7.2.1".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.2.1".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.2.1".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.2.1".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.2.1".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.6.1"]]
type = "missing_deps"

    [[Issues."7.6.1".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.6.1".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.6.1".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.6.1".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.6.1".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.5.0"]]
type = "missing_deps"

    [[Issues."7.5.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.5.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.5.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.5.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.5.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.5.1"]]
type = "missing_deps"

    [[Issues."7.5.1".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.5.1".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.5.1".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.5.1".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.5.1".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.11.0"]]
type = "missing_deps"

    [[Issues."7.11.0".deps]]
    name = "RespecializeParams"
    uuid = "9fe22ead-9e00-4db2-8b46-706a60d40f5e"

    [[Issues."7.11.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.11.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.11.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.11.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.11.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.9.0"]]
type = "missing_deps"

    [[Issues."7.9.0".deps]]
    name = "RespecializeParams"
    uuid = "9fe22ead-9e00-4db2-8b46-706a60d40f5e"

    [[Issues."7.9.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.9.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.9.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.9.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.9.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.0.0"]]
type = "missing_deps"

    [[Issues."7.0.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.0.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.0.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.0.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.0.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.4.0"]]
type = "missing_deps"

    [[Issues."7.4.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.4.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.4.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.4.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.4.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."6.216.0"]]
type = "missing_deps"

    [[Issues."6.216.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."6.216.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."6.216.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."6.216.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."6.216.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.6.0"]]
type = "missing_deps"

    [[Issues."7.6.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.6.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.6.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.6.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.6.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.5.7"]]
type = "missing_deps"

    [[Issues."7.5.7".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.5.7".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.5.7".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.5.7".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.5.7".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.5.2"]]
type = "missing_deps"

    [[Issues."7.5.2".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.5.2".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.5.2".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.5.2".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.5.2".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."6.214.1"]]
type = "missing_deps"

    [[Issues."6.214.1".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."6.214.1".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."6.214.1".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."6.214.1".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."6.214.1".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."7.1.0"]]
type = "missing_deps"

    [[Issues."7.1.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."7.1.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."7.1.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."7.1.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."7.1.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."6.215.0"]]
type = "missing_deps"

    [[Issues."6.215.0".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
    [[Issues."6.215.0".weak_deps]]
    name = "FlexUnits"
    uuid = "76e01b6b-c995-4ce6-8559-91e72a3d4e95"
    [[Issues."6.215.0".weak_deps]]
    name = "GTPSA"
    uuid = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
    [[Issues."6.215.0".weak_deps]]
    name = "GeneralizedGenerated"
    uuid = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
    [[Issues."6.215.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
