[Pkg]
name = "LanguageServer"
uuid = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
required = true

[Status]
version = "4.5.1"

[[Issues."5.0.0"]]
type = "missing_deps"

    [[Issues."5.0.0".deps]]
    name = "JuliaWorkspaces"
    uuid = "e554591c-7f10-434f-9f27-2097f62a04fd"
