[Pkg]
name = "ExponentialUtilities"
uuid = "d4d017d3-3776-5f7e-afef-a10c40355c18"

[Status]
version = "1.31.0"

[[Issues."1.35.0"]]
type = "missing_deps"

    [[Issues."1.35.0".deps]]
    name = "PureGebal"
    uuid = "78ab2635-e639-479d-9f80-4ef5c3b42ac6"
