[Pkg]
name = "NonlinearSolveBase"
uuid = "be0214bd-f91f-a760-ac4e-3421ce2b2da0"

[Status]
version = "2.11.2"

[[Issues."2.11.2"]]
type = "missing_deps"

    [[Issues."2.11.2".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
[[Issues."2.11.2"]]
dependent = []
dependency = ["PreallocationTools [d236fae5-4411-538c-8e31-a6e3d9e00b46]"]
type = "not_on_latest"
version = "2.11.2"
latest = "2.14.0"

[[Issues."2.12.0"]]
type = "missing_deps"

    [[Issues."2.12.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."2.14.0"]]
type = "missing_deps"

    [[Issues."2.14.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."2.13.0"]]
type = "missing_deps"

    [[Issues."2.13.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
