
[[Issues."1.4.3"]]
dependency = []
dependent = ["CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]"]
latest = "2.0.0"
type = "not_on_latest"
version = "1.4.3"
[[Issues."1.4.3"]]
type = "not_needed"
[Pkg]
name = "WeakRefStrings"
uuid = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[Status]
version = "1.4.3"
