
[[Issues."0.1.17"]]
dependency = ["SciMLBase [0bca4576-84f4-4d90-8ffe-ffa030f20462]"]
dependent = []
latest = "0.1.19"
type = "not_on_latest"
version = "0.1.17"
[Pkg]
name = "SciMLJacobianOperators"
uuid = "19f34311-ddf3-4b8b-af20-060888a46c0e"

[Status]
version = "0.1.17"
