
[[Issues."0.2.3"]]
dependency = []
dependent = ["Highlights [eafb193a-b7ab-5a9e-9068-77385905fa72]"]
latest = "0.3.1"
type = "not_on_latest"
version = "0.2.3"
[Pkg]
name = "TreeSitter"
uuid = "f42328cb-ece0-4cf2-995f-9e7abb27d006"

[Status]
version = "0.2.3"
