
[[Issues."1.1.4"]]
dependency = ["LLVM [929cbde3-209d-540e-8aea-75f648917ca0]", "UnsafeAtomics [013be700-e6cd-48c3-b4a1-df204f14c38f]"]
dependent = []
latest = "1.4.0"
type = "not_on_latest"
version = "1.1.4"
[Pkg]
name = "SPIRVIntrinsics"
uuid = "71d1d633-e7e8-4a92-83a1-de8814b09ba8"

[Status]
version = "1.1.4"
