[Status]
version = "1.1.0"

[[Issues."0.5.9"]]
version = "0.5.9"
type = "not_on_latest"
latest = "1.1.0"
dependent = ["OpenCL [08131aa3-fb12-5dee-8b74-c09406e224a2]"]
dependency = []

[Pkg]
name = "SPIRVIntrinsics"
uuid = "71d1d633-e7e8-4a92-83a1-de8814b09ba8"
