[Pkg]
name = "LLVMExtra_jll"
uuid = "dad2f222-ce93-54a1-a47d-0025e8a3acab"
is_jll = true

[Status]
version = "0.0.45+0"

[JLL.products]
library = ["libLLVMExtra"]

[[Issues."0.0.45+0"]]
dependent = ["LLVM [929cbde3-209d-540e-8aea-75f648917ca0]"]
dependency = []
type = "not_on_latest"
version = "0.0.45+0"
latest = "0.0.46+0"
