
[[Issues."0.0.47+0"]]
dependency = []
dependent = ["LLVM [929cbde3-209d-540e-8aea-75f648917ca0]"]
latest = "0.0.48+0"
type = "not_on_latest"
version = "0.0.47+0"

[JLL.products]
library = ["libLLVMExtra"]
[Pkg]
is_jll = true
name = "LLVMExtra_jll"
uuid = "dad2f222-ce93-54a1-a47d-0025e8a3acab"

[Status]
version = "0.0.47+0"
