[Pkg]
name = "BoundaryValueDiffEqFIRK"
uuid = "85d9eb09-370e-4000-bb32-543851f73618"

[Status]
version = "1.10.0"

[[Issues."1.10.0"]]
dependent = []
dependency = ["BoundaryValueDiffEqCore [56b672f2-a5fe-4263-ab2d-da677488eb3a]", "SciMLBase [0bca4576-84f4-4d90-8ffe-ffa030f20462]"]
type = "not_on_latest"
version = "1.10.0"
latest = "1.15.0"
