[Pkg]
name = "Optimization"
uuid = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
required = true

[Status]
version = "5.7.0"

[[Issues."5.7.0"]]
dependent = []
dependency = ["SciMLBase [0bca4576-84f4-4d90-8ffe-ffa030f20462]"]
type = "not_on_latest"
version = "5.7.0"
latest = "5.7.1"
