[Pkg]
name = "SymbolicUtils"
uuid = "d1185830-fcd6-423d-90d6-eec64667417b"

[Status]
version = "4.46.1"

[[Issues."4.46.1"]]
dependent = []
dependency = ["Moshi [2e0e35c7-a2e4-4343-998d-7ef72827ed2d]"]
type = "not_on_latest"
version = "4.46.1"
latest = "4.46.2"
