
[[Issues."0.8.1"]]
dependency = []
dependent = ["ImageSegmentation [80713f31-8817-5129-9cf8-209ff8fb23e1]"]
latest = "0.9.0"
type = "not_on_latest"
version = "0.8.1"
[Pkg]
name = "MetaGraphs"
uuid = "626554b9-1ddb-594c-aa3c-2596fe9399a5"

[Status]
version = "0.8.1"
