
[JLL.products]
executable = ["ffmpeg", "ffprobe"]
library = ["libavcodec", "libavdevice", "libavfilter", "libavformat", "libavutil", "libswresample", "libswscale"]
[Pkg]
is_jll = true
name = "FFMPEG_jll"
uuid = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"

[Status]
version = "9.0.2+0"
