[Pkg]
name = "FFMPEG_jll"
uuid = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
is_jll = true

[Status]
version = "8.1.2+0"

[JLL.products]
executable = ["ffmpeg", "ffprobe"]
library = ["libavcodec", "libavdevice", "libavfilter", "libavformat", "libavutil", "libswresample", "libswscale"]

[[Issues."8.1.2+0"]]
dependent = ["FFMPEG [c87230d0-a227-11e9-1b43-d7ebe4e7570a]", "Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a]", "VideoIO [d6d074c3-1acf-5d4c-9a43-ef38773959a2]"]
dependency = []
type = "not_on_latest"
version = "8.1.2+0"
latest = "9.0.0+0"
