[Pkg]
name = "HTTP"
uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[Status]
version = "1.11.0"

[[Issues."2.0.0"]]
type = "missing_deps"

    [[Issues."2.0.0".deps]]
    name = "Reseau"
    uuid = "802f3686-a58f-41ce-bb0c-3c43c75bba36"

[[Issues."2.3.0"]]
type = "missing_deps"

    [[Issues."2.3.0".deps]]
    name = "Reseau"
    uuid = "802f3686-a58f-41ce-bb0c-3c43c75bba36"

[[Issues."2.1.1"]]
type = "missing_deps"

    [[Issues."2.1.1".deps]]
    name = "Reseau"
    uuid = "802f3686-a58f-41ce-bb0c-3c43c75bba36"

[[Issues."2.4.0"]]
type = "missing_deps"

    [[Issues."2.4.0".deps]]
    name = "Reseau"
    uuid = "802f3686-a58f-41ce-bb0c-3c43c75bba36"

[[Issues."2.3.1"]]
type = "missing_deps"

    [[Issues."2.3.1".deps]]
    name = "Reseau"
    uuid = "802f3686-a58f-41ce-bb0c-3c43c75bba36"

[[Issues."2.2.0"]]
type = "missing_deps"

    [[Issues."2.2.0".deps]]
    name = "Reseau"
    uuid = "802f3686-a58f-41ce-bb0c-3c43c75bba36"

[[Issues."2.1.0"]]
type = "missing_deps"

    [[Issues."2.1.0".deps]]
    name = "Reseau"
    uuid = "802f3686-a58f-41ce-bb0c-3c43c75bba36"
