[Pkg]
name = "StochasticDiffEq"
uuid = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"

[Status]
version = "6.90.0"

[[Issues."6.101.0"]]
type = "missing_deps"

    [[Issues."6.101.0".deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"
    [[Issues."6.101.0".deps]]
    name = "StochasticDiffEqHighOrder"
    uuid = "0520c28c-50fd-4d16-9c96-902fc80b3bab"
    [[Issues."6.101.0".deps]]
    name = "StochasticDiffEqIIF"
    uuid = "ebf54054-c36b-4494-9aba-657e36df524f"
    [[Issues."6.101.0".deps]]
    name = "StochasticDiffEqImplicit"
    uuid = "5080b986-4c76-4669-b5dc-373a41579d5b"
    [[Issues."6.101.0".deps]]
    name = "StochasticDiffEqLeaping"
    uuid = "aefaaa88-39f2-4e89-b162-d61b7e8cc81b"
    [[Issues."6.101.0".deps]]
    name = "StochasticDiffEqLevyArea"
    uuid = "90dbc90e-856a-4131-af2c-e8c5aa0f35b5"
    [[Issues."6.101.0".deps]]
    name = "StochasticDiffEqLowOrder"
    uuid = "d15fe365-ce7f-450a-828a-7985bd5b681b"
    [[Issues."6.101.0".deps]]
    name = "StochasticDiffEqMilstein"
    uuid = "8c95a807-c8e7-4581-8419-890d001af53e"
    [[Issues."6.101.0".deps]]
    name = "StochasticDiffEqROCK"
    uuid = "db241ea8-0e6b-4abc-8f2d-1adff2294fd9"
    [[Issues."6.101.0".deps]]
    name = "StochasticDiffEqRODE"
    uuid = "49714585-0aa1-4f53-b1e6-a9b8c0d5e03f"
    [[Issues."6.101.0".deps]]
    name = "StochasticDiffEqWeak"
    uuid = "af2a2fcd-1c36-4cbe-a6d0-5afda784a085"
