[Pkg]
name = "Groebner"
uuid = "0b43b601-686d-58a3-8a1c-6623616c7cd4"

[Status]
version = "0.10.3"

[[Issues."0.10.4"]]
type = "missing_deps"

    [[Issues."0.10.4".deps]]
    name = "SmallCollections"
    uuid = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"

[[Issues."0.10.3"]]
type = "not_needed"
has_weak = true

[[Issues."0.10.5"]]
type = "missing_deps"

    [[Issues."0.10.5".deps]]
    name = "SmallCollections"
    uuid = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"
