[Pkg]
name = "DelayDiffEq"
uuid = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"

[Status]
version = "5.67.1"

[[Issues."5.70.0"]]
type = "missing_deps"

    [[Issues."5.70.0".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."5.71.0"]]
type = "missing_deps"

    [[Issues."5.71.0".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."5.67.1"]]
dependent = []
dependency = ["FastBroadcast [7034ab61-46d4-4ed7-9d0f-46aef9175898]", "OrdinaryDiffEqDifferentiation [4302a76b-040a-498a-8c04-15b101fed76b]"]
type = "not_on_latest"
version = "5.67.1"
latest = "5.71.0"
