[Pkg]
name = "DelayDiffEq"
uuid = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"

[Status]
version = "5.67.1"

[[Issues."6.0.5"]]
type = "missing_deps"

    [[Issues."6.0.5".deps]]
    name = "BinaryHeaps"
    uuid = "b2a6c25c-c996-4615-94ab-6e519ffb8690"

    [[Issues."6.0.5".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."6.0.3"]]
type = "missing_deps"

    [[Issues."6.0.3".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."6.0.6"]]
type = "missing_deps"

    [[Issues."6.0.6".deps]]
    name = "BinaryHeaps"
    uuid = "b2a6c25c-c996-4615-94ab-6e519ffb8690"

    [[Issues."6.0.6".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."6.0.1"]]
type = "missing_deps"

    [[Issues."6.0.1".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."6.0.7"]]
type = "missing_deps"

    [[Issues."6.0.7".deps]]
    name = "BinaryHeaps"
    uuid = "b2a6c25c-c996-4615-94ab-6e519ffb8690"

    [[Issues."6.0.7".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."5.74.1"]]
type = "missing_deps"

    [[Issues."5.74.1".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."6.0.4"]]
type = "missing_deps"

    [[Issues."6.0.4".deps]]
    name = "BinaryHeaps"
    uuid = "b2a6c25c-c996-4615-94ab-6e519ffb8690"

    [[Issues."6.0.4".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."5.67.1"]]
type = "not_needed"

[[Issues."5.70.0"]]
type = "missing_deps"

    [[Issues."5.70.0".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."6.0.2"]]
type = "missing_deps"

    [[Issues."6.0.2".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."5.74.0"]]
type = "missing_deps"

    [[Issues."5.74.0".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."5.73.0"]]
type = "missing_deps"

    [[Issues."5.73.0".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."5.71.0"]]
type = "missing_deps"

    [[Issues."5.71.0".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."5.72.0"]]
type = "missing_deps"

    [[Issues."5.72.0".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"

[[Issues."6.0.0"]]
type = "missing_deps"

    [[Issues."6.0.0".weak_deps]]
    name = "StochasticDiffEqCore"
    uuid = "19c5a474-6cd1-4a5f-be79-46dc34e54d7f"
