[Pkg]
name = "Enzyme"
uuid = "7da242da-08ed-463a-9acd-ee780be4f1d9"
required = true

[Status]
version = "0.13.196"

[[Issues."0.13.196"]]
type = "missing_deps"

    [[Issues."0.13.196".weak_deps]]
    name = "CUDA"
    uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
