[Pkg]
name = "DiffEqNoiseProcess"
uuid = "77a26b50-5914-5dd7-bc55-306e6241c503"

[Status]
version = "5.32.0"

[[Issues."5.32.0"]]
dependent = []
dependency = ["SciMLBase [0bca4576-84f4-4d90-8ffe-ffa030f20462]"]
type = "not_on_latest"
version = "5.32.0"
latest = "5.33.0"
