
[[Issues."1.2.6"]]
dependency = ["OrdinaryDiffEqLowOrderRK [1344f307-1e59-4825-a18e-ace9aa3fa4c6]", "RecursiveArrayTools [731186ca-8d62-57ce-b412-fbd966d074cd]", "SciMLBase [0bca4576-84f4-4d90-8ffe-ffa030f20462]", "StochasticDiffEq [789caeaf-c7a9-5a7d-9973-96adeb23e2a0]"]
dependent = []
latest = "1.2.9"
type = "not_on_latest"
version = "1.2.6"
[Pkg]
name = "QuantumOptics"
required = true
uuid = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"

[Status]
version = "1.2.6"
