[Pkg]
name = "NonlinearSolveFirstOrder"
uuid = "5959db7a-ea39-4486-b5fe-2dd0bf03d60d"

[Status]
version = "1.12.0"

[[Issues."1.12.0"]]
dependent = ["BoundaryValueDiffEqCore [56b672f2-a5fe-4263-ab2d-da677488eb3a]", "NonlinearSolve [8913a72c-1f9b-4ce2-8d82-65094dcecaec]"]
dependency = []
type = "not_on_latest"
version = "1.12.0"
latest = "2.0.0"
