[Pkg]
name = "aws_c_cal_jll"
uuid = "70f11efc-bab2-57f1-b0f3-22aad4e67c4b"
is_jll = true

[Status]
version = "0.9.13+0"

[JLL.products]
library = ["libaws_c_cal"]

[[Issues."0.9.13+0"]]
dependent = []
dependency = ["aws_c_common_jll [73048d1d-b8c4-5092-a58d-866c5e8d1e50]"]
type = "not_on_latest"
version = "0.9.13+0"
latest = "0.9.14+0"
