[Pkg]
name = "QuasiMonteCarlo"
uuid = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
required = true

[Status]
version = "0.3.11"

[[Issues."0.3.11"]]
dependent = ["MonteCarloIntegration [4886b29c-78c9-11e9-0a6e-41e1f4161f7b]"]
dependency = []
type = "not_on_latest"
version = "0.3.11"
latest = "0.4.0"
