[Pkg]
name = "OrdinaryDiffEqRosenbrock"
uuid = "43230ef6-c299-4910-a778-202eb28ce4ce"

[Status]
version = "1.21.0"

[[Issues."2.0.0"]]
type = "missing_deps"

    [[Issues."2.0.0".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"
