[Status]
version = "1.31.1"

[[Issues."2.3.1"]]
type = "missing_deps"

    [[Issues."2.3.1".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.3.2"]]
type = "missing_deps"

    [[Issues."2.3.2".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.2.0"]]
type = "missing_deps"

    [[Issues."2.2.0".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.4.0"]]
type = "missing_deps"

    [[Issues."2.4.0".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.3.0"]]
type = "missing_deps"

    [[Issues."2.3.0".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.4.1"]]
type = "missing_deps"

    [[Issues."2.4.1".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.6.3"]]
type = "missing_deps"

    [[Issues."2.6.3".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.6.0"]]
type = "missing_deps"

    [[Issues."2.6.0".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.6.1"]]
type = "missing_deps"

    [[Issues."2.6.1".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.0.0"]]
type = "missing_deps"

    [[Issues."2.0.0".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.6.2"]]
type = "missing_deps"

    [[Issues."2.6.2".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.4.2"]]
type = "missing_deps"

    [[Issues."2.4.2".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."2.1.0"]]
type = "missing_deps"

    [[Issues."2.1.0".deps]]
    name = "OrdinaryDiffEqRosenbrockTableaus"
    uuid = "b4bd8bb3-f80f-41d2-9b21-73a655b304b9"

[[Issues."1.21.0"]]
version = "1.21.0"
type = "not_on_latest"
latest = "2.6.3"
dependent = ["DelayDiffEq [bcd4f6db-9728-5f36-b5f7-82caef46ccdb]", "OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed]", "OrdinaryDiffEqDefault [50262376-6c5a-4cf5-baba-aaf4f84d72d7]"]
dependency = []

[Pkg]
name = "OrdinaryDiffEqRosenbrock"
uuid = "43230ef6-c299-4910-a778-202eb28ce4ce"
