[Pkg]
name = "Sundials"
uuid = "c3572dad-4567-51f8-b174-8c6c989267f4"
required = true

[Status]
version = "5.1.0"

[[Issues."5.1.0"]]
dependent = []
dependency = ["DataStructures [864edb3b-99cc-5e75-8d2d-829cb0a9cfe8]", "DiffEqBase [2b5f629d-d688-5b77-993f-72d75c75574e]"]
type = "not_on_latest"
version = "5.1.0"
latest = "6.2.2"
